builds:
  - binary: falco_postprocessor
    main: ./cmd/falco_postprocessor
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
release:
  prerelease: auto
universal_binaries:
  - replace: true
checksum:
  name_template: 'checksums.txt'
